DROP TABLE IF EXISTS `playlist_demo`;
CREATE TABLE IF NOT EXISTS `playlist_demo` (
  `playlist_item` int(11) NOT NULL AUTO_INCREMENT,
  `path` text NOT NULL,
  `subsong` int(11) DEFAULT NULL,
  `album` text DEFAULT NULL,
  `album_artist` text DEFAULT NULL,
  `artist` text DEFAULT NULL,
  `bitrate` int(11) DEFAULT NULL,
  `channels` int(11) DEFAULT NULL,
  `codec` text DEFAULT NULL,
  `codec_profile` text DEFAULT NULL,
  `comment` text DEFAULT NULL,
  `cuesheet` bit(1) DEFAULT NULL,
  `date` text DEFAULT NULL,
  `description` text DEFAULT NULL,
  `directoryname` text DEFAULT NULL,
  `discid` text DEFAULT NULL,
  `discnumber` text DEFAULT NULL,
  `filename` text DEFAULT NULL,
  `filename_ext` text DEFAULT NULL,
  `filesize` int(11) DEFAULT NULL,
  `filesize_natural` text DEFAULT NULL,
  `genre` text DEFAULT NULL,
  `label` text DEFAULT NULL,
  `label_serial` text DEFAULT NULL,
  `language` text DEFAULT NULL,
  `last_modified` datetime DEFAULT NULL,
  `length` time DEFAULT NULL,
  `length_seconds` double DEFAULT NULL,
  `mp3_accurate_length` text DEFAULT NULL,
  `mp3_stereo_mode` text DEFAULT NULL,
  `original_artist` text DEFAULT NULL,
  `original_release_date` text DEFAULT NULL,
  `pregap` text DEFAULT NULL,
  `publisher` text DEFAULT NULL,
  `rating` text DEFAULT NULL,
  `referenced_file` text DEFAULT NULL,
  `referenced_offset` time DEFAULT NULL,
  `release_type` text DEFAULT NULL,
  `releaser` text DEFAULT NULL,
  `releasetime` text DEFAULT NULL,
  `replaygain_reference_loudness` text DEFAULT NULL,
  `replaygain_track_gain` double DEFAULT NULL,
  `replaygain_track_peak` double DEFAULT NULL,
  `rip_date` text DEFAULT NULL,
  `ripping_tool` text DEFAULT NULL,
  `samplerate` int(11) DEFAULT NULL,
  `source` text DEFAULT NULL,
  `style` text DEFAULT NULL,
  `subtitle` text DEFAULT NULL,
  `tagtype` text DEFAULT NULL,
  `title` text DEFAULT NULL,
  `tool` text DEFAULT NULL,
  `totaldiscs` int(11) DEFAULT NULL,
  `totaltracks` int(11) DEFAULT NULL,
  `tracknumber` int(11) DEFAULT NULL,
  `transcoded_file` varchar(255) DEFAULT NULL,
  `transcoded_lifetime` datetime DEFAULT NULL,
  PRIMARY KEY (`playlist_item`),
  UNIQUE KEY `playlist_item` (`playlist_item`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table c5f.playlist_demo: ~2 rows (approximately)
INSERT INTO `playlist_demo` (`playlist_item`, `path`, `subsong`, `album`, `album_artist`, `artist`, `bitrate`, `channels`, `codec`, `codec_profile`, `comment`, `cuesheet`, `date`, `description`, `directoryname`, `discid`, `discnumber`, `filename`, `filename_ext`, `filesize`, `filesize_natural`, `genre`, `label`, `label_serial`, `language`, `last_modified`, `length`, `length_seconds`, `mp3_accurate_length`, `mp3_stereo_mode`, `original_artist`, `original_release_date`, `pregap`, `publisher`, `rating`, `referenced_file`, `referenced_offset`, `release_type`, `releaser`, `releasetime`, `replaygain_reference_loudness`, `replaygain_track_gain`, `replaygain_track_peak`, `rip_date`, `ripping_tool`, `samplerate`, `source`, `style`, `subtitle`, `tagtype`, `title`, `tool`, `totaldiscs`, `totaltracks`, `tracknumber`, `transcoded_file`, `transcoded_lifetime`) VALUES
	(1, './demo/Tokyo Machine/Pixel/PIXEL by TOKYO MACHINE.mp3', NULL, 'Pixel', 'Tokyo Machine', 'Tokyo Machine', 128, 2, 'MP3', 'CBR', NULL, b'0', '2017', NULL, './demo/Tokyo Machine/Pixel', NULL, NULL, 'PIXEL by TOKYO MACHINE', 'PIXEL by TOKYO MACHINE.mp3', 3451088, '3.28 Mb', 'EDM', NULL, NULL, NULL, NULL, '00:03:35', 215, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 44100, NULL, NULL, NULL, NULL, 'Pixel', NULL, NULL, 1, 1, NULL, NULL),
	(2, './demo/Tokyo Machine/Slash/SLASH by TOKYO MACHINE.mp3', NULL, 'Slash', 'Tokyo Machine', 'Tokyo Machine', 128, 2, 'MP3', 'CBR', NULL, b'0', '2022', NULL, './demo/Tokyo Machine/Slash', NULL, NULL, 'SLASH by TOKYO MACHINE', 'SLASH by TOKYO MACHINE.mp3', 2814954, '2.68 Mb', 'EDM', NULL, NULL, NULL, NULL, '00:02:55', 175, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 44100, NULL, NULL, NULL, NULL, 'Slash', NULL, NULL, 1, 1, NULL, NULL);
